name: Node.js matrix CI 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18, 20]
    name: Node ${{ matrix.node }} sample
    steps:
      - name: Git clone
        uses: actions/checkout@v3
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          npm install
          chmod u+x ./node_modules/.bin/*
      - name: Run unit tests
        run: npm test
